name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  check_commit:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check_commit_message.outputs.should_deploy }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check Commit Message
        id: check_commit_message
        run: |
          commit_message=$(git log -1 --pretty=%B)
          echo "Commit message: $commit_message"
          if [[ $commit_message == *"deploy: main"* ]]; then
            echo "Commit message contains 'deploy: main'."
            echo "::set-output name=should_deploy::true"
          else
            echo "Commit message does not contain 'deploy: main'."
            echo "::set-output name=should_deploy::false"
          fi

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: check_commit
    if: needs.check_commit.outputs.should_deploy == 'true'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install node dependencies
      run: npm install

    - name: Install Serverless Framework
      run: npm install -g serverless

    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: serverless deploy